[build]
  command = "vite build"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200