[build]
  command = "npm run build"  # or "yarn build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200